version: '3'

services:
  onlyoffice:
    container_name: mistborn_production_onlyoffice
    image: onlyoffice/documentserver:latest
    volumes:
      - ../../mistborn_volumes/extra/onlyoffice/logs:/var/log/onlyoffice
      - ../../mistborn_volumes/extra/onlyoffice/cache:/var/lib/onlyoffice
    env_file:
      - ../.envs/.production/.onlyoffice
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onlyoffice-http.rule=Host(`onlyoffice.mistborn`)"
      - "traefik.http.routers.onlyoffice-http.entrypoints=web"
      - "traefik.http.routers.onlyoffice-http.middlewares=mistborn_auth@file"
      - "traefik.http.routers.onlyoffice-https.rule=Host(`onlyoffice.mistborn`)"
      - "traefik.http.routers.onlyoffice-https.entrypoints=websecure"
      - "traefik.http.routers.onlyoffice-https.middlewares=mistborn_auth@file"
      - "traefik.http.routers.onlyoffice-https.tls.certresolver=basic"
      - "traefik.http.services.onlyoffice-service.loadbalancer.server.port=80"
    restart: unless-stopped 

networks:
  default:
    external:
      name: mistborn_default
