version: '3'

services:
  raspap:
    image: "cyber5k/raspap:${MISTBORN_TAG}"
    container_name: mistborn_production_raspap
    #network_mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raspap-http.rule=Host(`raspap.mistborn`)"
      - "traefik.http.routers.raspap-http.entrypoints=web"
      - "traefik.http.routers.raspap-http.middlewares=mistborn_auth@file"
      - "traefik.http.routers.raspap-https.rule=Host(`raspap.mistborn`)"
      - "traefik.http.routers.raspap-https.entrypoints=websecure"
      - "traefik.http.routers.raspap-https.middlewares=mistborn_auth@file"
      - "traefik.http.routers.raspap-https.tls.certresolver=basic"
      - "traefik.http.services.raspap-service.loadbalancer.server.port=80"
    env_file:
      - ../.envs/.production/.raspap
    cap_add:
      #- NET_ADMIN
      - SYS_ADMIN
      #- CAP_FOWNER
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    #command: /start
    restart: unless-stopped

networks:
  default:
    external:
      name: mistborn_default
