version: '3'

services:
  tor-client:
    build:
      context: ../compose/production/tor
      dockerfile: ./Dockerfile
    image: mistborn_production_tor
    container_name: mistborn_production_tor
    ports:
      - "${MISTBORN_BIND_IP}:9150:9150/tcp"

networks:
  default:
    external:
      name: mistborn_default
